### ISSUE TITLE
Create HTTP callback mode for the .NET (C#) library

### ISSUE THREAD

**Issue by pseabury** [yoctopuce/yoctolib_cs#1]
Using this mode for an ASP.NET application hosted in the cloud would be great.  Should be similar to the java solution here - http://www.yoctopuce.com/EN/article/using-http-callback-with-java

**Comment by yoctopuce** [comment]
This makes sense. We have added this feature request to our todo list, but do not expect this feature to be added in the near future since we are now fully focused on the release of new products.

**Comment by yoctopuce** [comment]
Remove it from our to-do list due to a lack of interest from other customers.
