### ISSUE TITLE
Mbed-TLS dependency may need updating to address a security vulnerability

### ISSUE THREAD

**Issue by MikeFarrington** [yoctopuce/yoctolib_cs#2]
Mbed-TLS was [updated to v3.62](https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-3.6.2) to address a [buffer underrun vulnerability](https://mbed-tls.readthedocs.io/en/latest/security-advisories/mbedtls-security-advisory-2024-10-1/) on 15-OCT-24, which is after the [most recent release of this repository on 10-OCT-24](https://github.com/yoctopuce/yoctolib_cs/releases/tag/v2.0.62875).

Could you please address this and re-release (or issue a statement stating that this vulnerability does not apply, if that is the case).

**Comment by srinsoz** [comment]
We were hoping to release a new build with the latest version of Mbed-TLS today, but a minor bug has postponed the release until next week. Anyway, the update is coming soon.

**Comment by srinsoz** [comment]
Fixed in the last release
